server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*" # FRONT URL?
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
      routes:
        - id: auth
          uri: lb://AUTH
          predicates:
            - Path=/api/v1/auth/**
        - id: land
          uri: lb://LAND
          predicates:
            - Path=/api/v1/lands/**
        - id: iSale
          uri: lb://ISALE
          predicates:
            - Path=/api/v1/iSale/**