spring:
  application:
    name: auth
  profiles:
    active: test
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost:3306/auth_test?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 9001